export const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_CODES = {
    // Auth & User Errors
    AUTH_REQUIRED: "AUTH_REQUIRED",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",

    // Request & Input Validation Errors
    VALIDATION_ERROR: "VALIDATION_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    NOT_FOUND: "NOT_FOUND",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",

    // Security & Rate Limiting
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

    // System Errors
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCodeType = typeof ERROR_CODES[keyof typeof ERROR_CODES];

class ErrorList {
    static HTTP_STATUS = HTTP_STATUS;
    static ERROR_CODES = ERROR_CODES;

    // Backward compatibility helpers
    static BAD_REQUEST = HTTP_STATUS.BAD_REQUEST;
    static UNAUTHORIZED = HTTP_STATUS.UNAUTHORIZED;
    static FORBIDDEN = HTTP_STATUS.FORBIDDEN;
    static NOT_FOUND = HTTP_STATUS.NOT_FOUND;
    static CONFLICT = HTTP_STATUS.CONFLICT;
    static INTERNAL_SERVER_ERROR = HTTP_STATUS.INTERNAL_SERVER_ERROR;
}

export default ErrorList;